### ISSUE TITLE
Automatic split on maps

### ISSUE THREAD

**Issue by mrWrm** [brandondong/POE-LiveSplit-Component#1]
Hi,

I was wondering if it would be technically possible to extend this to automatically split on different maps, so you could track how fast you can do certain maps?

Thanks for a nice component

**Comment by brandondong** [comment]
Hi, apologies for this late reply. I must have missed this.

While this idea is definitely technically possible, I am having a difficult time imagining how the usage of this would work. Splits in speedruns are generally used to record milestones in a linear progression. With maps, your choice in the order of them to run is not fixed. The best use case I can think of would be one where you create for example 10 splits, run 10 Gorge's, and have the timer automatically track the time it took for each map. Is this similar to what you had in mind?

**Comment by zombodotcom** [comment]
This already exists. Mapwatch
