### ISSUE TITLE
activate/settings button inactive

### ISSUE THREAD

**Issue by jeske** [brandondong/POE-LiveSplit-Component#10]
I followed the instructions... but the "settings" and "activate" buttons are greyed out. 

The instructions just say to install LiveSplit, is this component included automatically? Is there some way to add it manually?

![image](https://user-images.githubusercontent.com/15093/112659906-1c487c00-8e12-11eb-9dda-1e7d45642cb3.png)

**Comment by jeske** [comment]
I found the problem..

LiveSplit does not work properly if extracted to the "Program Files" directory... I guess it tries to write it's files into the LiveSplit directory, instead of using `$HOME\AppData\Local\LiveSplit` like it should.

You could change the instructions to explicitly state not to put LiveSplit into the ProgramFiles directory, as this is a very standard and common thing for windows users to do.

**Comment by brandondong** [comment]
LiveSplit writes files into whatever directory you extract it into. You can extract it to anywhere you want; it doesn't need to be in AppData.

The exception to this is extracting it into a folder that requires Administrator access (e.g. Program Files). LiveSplit won't have write access so all its IO operations will fail which it does not handle too gracefully.

This is not the first time someone has run into this: https://github.com/brandondong/POE-LiveSplit-Component/issues/7. I'll make sure to update the README to clarify this.

**Comment by brandondong** [comment]
Fixed in https://github.com/brandondong/POE-LiveSplit-Component/commit/887d1ce4d76d4b382ec49140d477a97b18c73c8f.

**Comment by jeske** [comment]
Im not saying livesplit needs to be unzipped into AppData.. im saying liveaplit should write their local data files into AppData/Local/Appname no matter where it is unzipped to.. 

$HOME/AppData/Local/Appname is the modern windows equivalent to unix home directory dotfiles , aka ~/.appname

**Comment by brandondong** [comment]
Ahh I see what you mean. Apologies for the misunderstanding.
