### ISSUE TITLE
There is no auto splitter available for this game

### ISSUE THREAD

**Issue by toddy1b21** [brandondong/POE-LiveSplit-Component#15]
I have followed the Setup and Extract the zip file into a convenient folder.
but cannot  click the Activate button .
I have found the same issue ,the issues/7,
and I are not able to reach
https://github.com/brandondong/POE-LiveSplit-Component/raw/master/POELiveSplitComponent/Update/Components/POELiveSplitComponent.dll 
with a browser.

It shows ERR_CONNECTION_RESET

plz help me thank you

**Comment by brandondong** [comment]
The link works fine for me (it should prompt the browser to perform a download).

Are you able to activate any other autosplitter? For example, if you type the game name "Portal", are you able to click Activate in that case? Also, please confirm the extracted zip contents are in a folder without requiring administrative permissions.
