### ISSUE TITLE
Ending Zone in livesplit change

### ISSUE THREAD

**Issue by lArtaEval** [brandondong/POE-LiveSplit-Component#16]
As currently Oriath doesn't exist anymore for campaign end zone and it doesn't autosplit as we enter Karui Shores (new last Zone).

**Comment by lArtaEval** [comment]
Don't want to make new thread, is there possibility to make Autosplit to split after Campaign(by zone) by levels (for example 70+)?

**Comment by brandondong** [comment]
I pushed the zone fix. To get the change, restart LiveSplit and an update prompt should appear in a couple of seconds.

With regards to splitting on levels after the campaign, that is not currently possible but I could look to implement that as a new feature.

**Comment by lArtaEval** [comment]
Would be awesome if you could, as some people really would like to have such option. Ty for such fast respond. =)

**Comment by brandondong** [comment]
I pushed another update. Levels can now be selected below the list of campaign zones.
![image](https://user-images.githubusercontent.com/13722457/185814204-b4ac506f-797b-44f5-a39b-4af83fa77ca7.png)

**Comment by lArtaEval** [comment]
Thank you very much!
