### ISSUE TITLE
how to use it in korean?

### ISSUE THREAD

**Issue by JuneCho695** [brandondong/POE-LiveSplit-Component#18]
I want to use this in Korean. Should I change the names of zones to Korean on zone.cs? Are there any points to note when building?

**Comment by CypherConjured** [comment]
Not sure if this helps, but there's a korean fork, you may get some hints there (it's two years old though): [https://github.com/luensys/POE-LiveSplit-Component](https://github.com/luensys/POE-LiveSplit-Component)

**Comment by JuneCho695** [comment]
Thank you.
