### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ohlawdie** [brandondong/POE-LiveSplit-Component#2]
Hey Brandon, I just wanted to say thanks for making this! I have yet to get in-game to test it out but I imagine it works as intended. Is it pretty trivial to add our own splits based off different loading zones?

**Comment by brandondong** [comment]
Hi, you can set which zones you would prefer to have automatically split in the settings menu as well as generate those splits automatically. Hopefully the setup instructions in the README are explained clearly enough. Thanks for your kind words.
