### ISSUE TITLE
Autosplit is not working properly

### ISSUE THREAD

**Issue by xand1r** [brandondong/POE-LiveSplit-Component#20]
Hi.
So problem is switching the autosplit to the next zone in the list, but in fact this zone has not yet been visited
For example, I start the timer in Lioneye's Watch, then I go to The Coast, autosplit switches to The Cost (this is correct), but if I immediately return from the coast back to the city, then the autosplit switches to Tidal Island (which is not correct)
Logs from game int this time
2023/08/11 15:58:56 79602687 cffb0719 [INFO Client 7540] : You have entered Lioneye's Watch.
2023/08/11 15:58:56 79603000 32758e3a [INFO Client 7540] [SHADER] Delay: ON
2023/08/11 16:00:33 79699796 cffb0719 [INFO Client 7540] DFourSeasonTwoWaitingRo: hi
2023/08/11 16:13:58 80504406 cffb0719 [INFO Client 7540] : AFK mode is now ON. Autoreply "This player is AFK."
2023/08/11 16:16:42 80668937 cffb0719 [INFO Client 7540] : AFK mode is now OFF.
2023/08/11 16:19:51 80858000 88a90547 [DEBUG Client 7540] Got Instance Details from login server
2023/08/11 16:19:51 80858000 84a7dab9 [INFO Client 7540] [ENGINE] Warmup: ON
2023/08/11 16:19:51 80858000 340884f9 [INFO Client 7540] [RENDER] Warmup: ON
2023/08/11 16:19:51 80858000 32758e1f [INFO Client 7540] [SHADER] Warmup: ON
2023/08/11 16:19:51 80858000 b740341a [INFO Client 7540] [DOWNLOAD] Pre-downloading "Content/Data/WorldAreas/1_1_2"
2023/08/11 16:19:51 80858000 b740341a [INFO Client 7540] [DOWNLOAD] Pre-downloading "Streaming/Content/Data/WorldAreas/1_1_2"
2023/08/11 16:19:51 80858000 32758e3a [INFO Client 7540] [SHADER] Delay: OFF
2023/08/11 16:19:51 80858000 ca3a6a70 [INFO Client 7540] Connecting to instance server at 212.118.227.106:6112
2023/08/11 16:19:51 80858078 ca3a4dbc [DEBUG Client 7540] Connect time to instance server was 78ms
2023/08/11 16:19:51 80858140 1186a0e4 [DEBUG Client 7540] Generating level 2 area "1_1_2" with seed 3544749386
2023/08/11 16:19:52 80858687 f22b6986 [INFO Client 7540] Tile hash: 3732553710
2023/08/11 16:19:52 80858687 f22b6989 [INFO Client 7540] Doodad hash: 4177559706
2023/08/11 16:19:52 80859000 11870f48 [DEBUG Client 7540] Joined guild named Russian Bears with 159 members 
2023/08/11 16:19:53 80859312 cffb0719 [INFO Client 7540] : You have entered The Coast.
2023/08/11 16:19:53 80859781 32758e3a [INFO Client 7540] [SHADER] Delay: ON
2023/08/11 16:19:58 80864671 88a90547 [DEBUG Client 7540] Got Instance Details from login server
2023/08/11 16:19:58 80864687 84a7dab9 [INFO Client 7540] [ENGINE] Warmup: ON
2023/08/11 16:19:58 80864687 340884f9 [INFO Client 7540] [RENDER] Warmup: ON
2023/08/11 16:19:58 80864687 32758e1f [INFO Client 7540] [SHADER] Warmup: ON
2023/08/11 16:19:58 80864687 b740341a [INFO Client 7540] [DOWNLOAD] Pre-downloading "Content/Data/WorldAreas/1_1_town"
2023/08/11 16:19:58 80864687 b740341a [INFO Client 7540] [DOWNLOAD] Pre-downloading "Streaming/Content/Data/WorldAreas/1_1_town"
2023/08/11 16:19:58 80864687 32758e3a [INFO Client 7540] [SHADER] Delay: OFF
2023/08/11 16:19:58 80864687 ca3a6a70 [INFO Client 7540] Connecting to instance server at 103.50.32.34:6112
2023/08/11 16:19:58 80864734 ca3a4dbc [DEBUG Client 7540] Connect time to instance server was 47ms
2023/08/11 16:19:58 80864781 1186a0e4 [DEBUG Client 7540] Generating level 13 area "1_1_town" with seed 1
2023/08/11 16:19:58 80865203 f22b6986 [INFO Client 7540] Tile hash: 3254420771
2023/08/11 16:19:58 80865203 f22b6989 [INFO Client 7540] Doodad hash: 2393431363
2023/08/11 16:19:59 80865578 11870f48 [DEBUG Client 7540] Joined guild named Russian Bears with 159 members 
2023/08/11 16:19:59 80865890 cffb0719 [INFO Client 7540] : You have entered Lioneye's Watch.
2023/08/11 16:19:59 80866265 32758e3a [INFO Client 7540] [SHADER] Delay: ON

![Untitled](https://github.com/brandondong/POE-LiveSplit-Component/assets/61163002/f56ff23e-8014-489f-86d6-8d5d8598024f)

**Comment by brandondong** [comment]
There isn't a one-to-one mapping between the zones you've chosen to autosplit on and the split names (which can be any arbitrary string and of arbitrary number). The Generate Splits button is just a utility to help with the tedious process of creating all those splits in the first place. You can rename them as you like and if you take a different route through Act 2 for example, you'll need to re-order the generated split names.

Any time you enter a zone that is checked for autosplitting for the first time, the timer will simply advance to the next split down the list. If you're planning to start your speedruns in Lioneye's Watch and not in The Twilight Strand, I would recommend just unticking Lioneye's Watch for autosplitting.

Hope that helps.

**Comment by xand1r** [comment]
Thanks for the answer, I just thought that it works a little differently and autosplit is triggered by the name of the zone in the game logs.
