### ISSUE TITLE
Auto split not working?

### ISSUE THREAD

**Issue by jnitis** [brandondong/POE-LiveSplit-Component#4]
So I generate the splits, they generate fine and I start my run.  I'm a few zones in but it doesn't seem to gather that and starts from the beginning.  Also, it only auto-splits every time I enter a new zone, regardless of the zone name.  ie, it seems to understand I enter a new zone but not which zone.

I could be doing something wrong as this is my first time using livesplit.

Cheers!

**Comment by brandondong** [comment]
Hi,
The tool is simply designed to automatically split whenever you enter any one the zones you've selected for the first time. That logic is entirely separate to the naming, number, or order of your splits.

In LiveSplit, splits always progress sequentially as they represent a linear progression of the milestones of your run. If you want to practice a speedrun starting at its halfway point, LiveSplit allows skipping splits (NumPad 2 by default).

The automatic split generation feature is simply added for convenience as usually runners name their splits after the zone names they want to split on. Feel free to rename them if you prefer other names, reorder them if you progress through zones differently, create your own splits between them if you want to manually track events not covered by the tool like boss kills, or ignore the feature altogether and manually create all the splits for your run.

Hope this helps. Please let me know if anything is still unclear.
