### ISSUE TITLE
Can't setup autosplitter

### ISSUE THREAD

**Issue by Gavisa** [brandondong/POE-LiveSplit-Component#7]
Hello, just downloaded this and the last version of livesplit and its my first time trying to use this program so maybe I'm just making a stupid mistake, but from what I've read from your readme file, I cant come to install this autosplit since the "Activate" button is not clickable even when I write "Path of Exile" in the game name field. I've read online that I should place the dll file into the components but even after that I couldnt press "Activate". Do you have any idea of what I could be doing wrong? Im sure this is just me missing something.

**Comment by brandondong** [comment]
Hi, a screenshot would be useful in helping diagnose the issue.
![image](https://user-images.githubusercontent.com/13722457/76136744-edcee780-5fe9-11ea-9063-3b94457fc9f0.png)
This is what it should look like.

Are you able to activate any other autosplitter? For example, if you type the game name "Portal", are you able to click Activate in that case?

If so, I would first try restarting LiveSplit. If that doesn't work, try opening the folder location of your LiveSplit executable, and navigating to the Components folder. If there is a POELiveSplitComponent.dll file in that folder, try deleting it and then reopening LiveSplit.
If the file isn't already there after you've searched up the game name, that would be quite strange and may suggest that this is an issue with LiveSplit itself. It would be good to confirm that you are able to reach https://github.com/brandondong/POE-LiveSplit-Component/raw/master/POELiveSplitComponent/Update/Components/POELiveSplitComponent.dll with a browser.

Please let me know how this goes.

**Comment by Gavisa** [comment]
I tried for the third time now to reinstall the whole application and did it on a new folder with all permissions granted and it worked! Thanks for the help and specially the picture, if I didn't see the "Website" missing I wouldn't have thought it was such a big error.

It seems not even other were autosplitters were working. 

![image](https://user-images.githubusercontent.com/30677923/76141948-9c157400-6060-11ea-97c0-af1c8684536c.png)

**Comment by brandondong** [comment]
Glad the issue was resolved.
